agentName: "MultiFormatSummarizerAgent"
agentDescription: "An intelligent document summarization agent that creates concise, accurate summaries from PDFs, images, Word docs, Excel files, and text content using advanced AI models and OCR technology"
agentInstruction: "You are a helpful document summarization assistant. When users provide text content or upload documents (PDFs, images, Word docs, Excel files, etc.), analyze the content carefully and create a clear, concise summary that captures the main points and key information. For images, use OCR to extract text first, then summarize. Focus on accuracy and readability while maintaining the essential meaning of the original content."

foundationModel:
  modelId: "anthropic.claude-3-sonnet-20240229-v1:0"
  inferenceParams:
    max_tokens: 300
    temperature: 0.3
    top_p: 0.9

actionGroups:
  - actionGroupName: "summarizeText"
    actionGroupExecutor: "arn:aws:lambda:REGION:ACCOUNT_ID:function:summarizer_function"
    apiSchema:
      openAPISchema:
        openapi: 3.0.1
        info:
          title: "Multi-Format Document Summarization API"
          version: "2.0"
          description: "API for summarizing text content and documents (PDFs, images, Word docs, Excel files) using AI models and OCR"
        paths:
          /summarize:
            post:
              summary: "Summarize text content or documents"
              description: "Takes input text or file content and returns a concise summary"
              requestBody:
                required: true
                content:
                  application/json:
                    schema:
                      type: object
                      properties:
                        input:
                          type: string
                          description: "The text content to be summarized"
                          minLength: 1
                          maxLength: 10000
                        file_content:
                          type: string
                          description: "Base64 encoded file content"
                        filename:
                          type: string
                          description: "Name of the uploaded file"
                      anyOf:
                        - required: ["input"]
                        - required: ["file_content", "filename"]
              responses:
                '200':
                  description: "Successful summarization"
                  content:
                    application/json:
                      schema:
                        type: object
                        properties:
                          summary:
                            type: string
                            description: "The generated summary"
                          source:
                            type: string
                            description: "Source of the input (text or file info)"
                          input_length:
                            type: integer
                            description: "Length of input text"
                          summary_length:
                            type: integer
                            description: "Length of generated summary"
                '400':
                  description: "Bad request - invalid input"
                '500':
                  description: "Internal server error"

# Agent metadata for marketplace
agentMetadata:
  version: "1.0.0"
  author: "Your Name"
  category: "Productivity"
  tags:
    - "summarization"
    - "document-processing"
    - "ocr"
    - "pdf-processing"
    - "image-processing"
    - "ai"
    - "productivity"
  pricing:
    model: "per-request"
    cost: "0.001"
    currency: "USD"
  support:
    email: "support@yourdomain.com"
    documentation: "https://your-docs-url.com"
