agentName: "DocumentIntelligenceAgent"
agentDescription: "An advanced document intelligence agent that can understand, analyze, and interact with documents in multiple formats. Capable of summarization, Q&A, entity extraction, translation, classification, sentiment analysis, and more using AWS Agent Core and Claude 3 Sonnet."
agentInstruction: "You are an intelligent document processing assistant with multiple capabilities. When users provide documents or text, you can: 1) Summarize content intelligently, 2) Answer questions about documents, 3) Extract entities (people, organizations, dates), 4) Translate content, 5) Classify document types, 6) Extract insights and patterns, 7) Analyze sentiment, 8) Find action items and deadlines, 9) Search for specific information. Always explain your reasoning and provide confidence levels for your analysis. Maintain context across interactions and adapt your approach based on user queries."

foundationModel:
  modelId: "anthropic.claude-3-sonnet-20240229-v1:0"
  inferenceParams:
    max_tokens: 300
    temperature: 0.3
    top_p: 0.9

actionGroups:
  - actionGroupName: "summarizeText"
    actionGroupExecutor: "arn:aws:lambda:REGION:ACCOUNT_ID:function:document_intelligence_function"
    apiSchema:
      openAPISchema:
        openapi: 3.0.1
        info:
          title: "Document Intelligence Agent API"
          version: "3.0"
          description: "Advanced API for document intelligence including summarization, Q&A, entity extraction, translation, classification, and more using AWS Agent Core"
        paths:
          /process:
            post:
              summary: "Process documents with intelligent agent capabilities"
              description: "Takes input text or file content and user query, returns intelligent analysis based on agent decision-making"
              requestBody:
                required: true
                content:
                  application/json:
                    schema:
                      type: object
                      properties:
                        input:
                          type: string
                          description: "The text content to be processed"
                          minLength: 1
                          maxLength: 10000
                        file_content:
                          type: string
                          description: "Base64 encoded file content"
                        filename:
                          type: string
                          description: "Name of the uploaded file"
                        user_query:
                          type: string
                          description: "User query or instruction for the agent"
                          minLength: 1
                          maxLength: 1000
                      anyOf:
                        - required: ["input", "user_query"]
                        - required: ["file_content", "filename", "user_query"]
              responses:
                '200':
                  description: "Successful summarization"
                  content:
                    application/json:
                      schema:
                        type: object
                        properties:
                          agent_response:
                            type: string
                            description: "The agent's intelligent response"
                          source:
                            type: string
                            description: "Source of the input (text or file info)"
                          user_query:
                            type: string
                            description: "The user's original query"
                          agent_action:
                            type: string
                            description: "Action chosen by the agent"
                          confidence:
                            type: number
                            description: "Agent's confidence in the analysis"
                          reasoning:
                            type: string
                            description: "Agent's reasoning for the chosen action"
                          input_length:
                            type: integer
                            description: "Length of input text"
                '400':
                  description: "Bad request - invalid input"
                '500':
                  description: "Internal server error"

# Agent metadata for marketplace
agentMetadata:
  version: "1.0.0"
  author: "Your Name"
  category: "Productivity"
  tags:
    - "document-intelligence"
    - "ai-agent"
    - "document-processing"
    - "ocr"
    - "pdf-processing"
    - "image-processing"
    - "qa"
    - "translation"
    - "entity-extraction"
    - "sentiment-analysis"
    - "ai"
    - "productivity"
  pricing:
    model: "per-request"
    cost: "0.001"
    currency: "USD"
  support:
    email: "support@yourdomain.com"
    documentation: "https://your-docs-url.com"
